version: '3'
services:
  web:
    build: .
    ports:
      - "8083:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
